### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by damianbl** [gajus/seeql#10]
Hi,
I'd love to use your tool (and contribute as well) but I have a problem using it with my app/database.

This is how I start it:

`node /usr/local/bin/seeql --database-host localhost --database-database database_name --database-password database_password --database-user database_user --service-port 3307
`

When I try to connect to the service with the app or any client the service stops with the following error:

```
TypeError: Cannot read property 'toString' of undefined
    at /usr/local/lib/node_modules/seeql/node_modules/blessed-contrib/lib/widget/table.js:86:30
    at Array.forEach (native)
    at dataToString (/usr/local/lib/node_modules/seeql/node_modules/blessed-contrib/lib/widget/table.js:83:7)
    at /usr/local/lib/node_modules/seeql/node_modules/blessed-contrib/lib/widget/table.js:104:15
    at Array.forEach (native)
    at Table.setData (/usr/local/lib/node_modules/seeql/node_modules/blessed-contrib/lib/widget/table.js:102:14)
    at table.setData (/usr/local/lib/node_modules/seeql/dist/index.js:98:9)
    at Query.onResult (/usr/local/lib/node_modules/seeql/dist/index.js:161:9)
    at /usr/local/lib/node_modules/seeql/node_modules/mysql2/lib/commands/query.js:66:14
    at doNTCallback0 (node.js:419:9)
```

It looks like it it fails in _blessed-contrib_. 

Did you experience that issue before?

**Comment by gajus** [comment]
Hi @damianbl,

Can you give some information about the environment?

Node.js version, OS version, NPM version.

**Comment by damianbl** [comment]
H @gajus,

NPM: 4.1.2
Nojde.js: 7.7.3 ( I tried different versions too)
OS version: MacOS Sierra 10.12.3
