### ISSUE TITLE
address already in use.

### ISSUE THREAD

**Issue by Chris2011** [gajus/seeql#15]
When I try to connect to my DB with correct credentials and all, I got this message:

```
Error: listen EADDRINUSE: address already in use :::3306
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Server.listen (C:\Users\Chrl\AppData\Roaming\npm\node_modules\seeql\node_modules\mysql2\lib\server.js:28:25)
    at Object.<anonymous> (C:\Users\Chrl\AppData\Roaming\npm\node_modules\seeql\dist\index.js:188:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Is there a need to change the port or what? I thought it is listening on that port.

**Comment by Chris2011** [comment]
Command that I want to call: `seeql --database-host=localhost --databse-user=root --database-password --database-database=mydb`

Using Windows 10 64Bit and Wampserver64
